spring.application.name=orders-api

spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===========================
# AWS Cognito
# ===========================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_BSwlfbdiE

aws.cognito.user-pool-id=${COGNITO_USER_POOL_ID}
aws.cognito.client-id=${COGNITO_CLIENT_ID}
aws.cognito.region=us-east-1